[package]
name = "libafl-aptos"
edition.workspace = true
version.workspace = true

[dependencies]
libafl = { workspace = true }
libafl_bolts = { workspace = true }
aptos-generator = { workspace = true }
aptos-mutator = { workspace = true }
aptos-objective = { workspace = true }
aptos-afl-executor = { workspace = true }
aptos-fuzzer-state = { workspace = true }