[package]
name = "libafl-aptos"
edition.workspace = true
version.workspace = true

[dependencies]
libafl = { workspace = true }
libafl_bolts = { workspace = true }
aptos-fuzzer-mutator = { workspace = true }
aptos-fuzzer-executor = { workspace = true }
aptos-fuzzer-state = { workspace = true }