[workspace]

resolver = "2"
members = [
    "bin/*",
    "crates/fuzzer-core",
    "crates/sui-tracer",
    "crates/sui-fuzzer",
    "crates/sui-simulator",
]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
async-trait = "0.1"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
lru = "0.16"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.45", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
bcs = "0.1.4"
eyre = "0.6"
thiserror = "2.0"
hex = "0.4"

# Sui Specific dependencies
sui-sdk = { git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-types = { git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-config = { git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-json-rpc = { git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-json-rpc-types = { git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-core = { git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-execution = { git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer", features = [
    "tracing",
] }
sui-storage = { git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-protocol-config = { git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
# Rename to avoid conflict with aptos move crates
sui-move-core-types = { package = "move-core-types", git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-move-vm-types = { package = "move-vm-types", git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-move-binary-format = { package = "move-binary-format", git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-move-trace-format = { package = "move-trace-format", git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-move-bytecode-utils = { package = "move-bytecode-utils", git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-move-vm-config = { package = "move-vm-config", git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
sui-move-vm-runtime = { package = "move-vm-runtime", git = "https://github.com/fuzzland/sui.git", branch = "mainnet-v1.55.0-dryrun-with-tracer" }
schemars = "1.0"

# Aptos Specific dependencies
aptos-config = { git = "https://github.com/fuzzland/aptos-core", rev = "1e5097063214a84f794ed2373f66a9d325bf6ca4" }
