[workspace]
resolver = "2"
members = ["bin/*"]

[workspace.dependencies]
async-trait = "0.1"
anyhow = "1.0"
aptos-private-node = { git = "https://github.com/fuzzland/aptos-node.git", branch = "main", package = "aptos-private-node" }