[package]
name = "aptos-mutator"
edition.workspace = true
version.workspace = true

[dependencies]
libafl = { workspace = true }
libafl_bolts = { workspace = true }
aptos-fuzzer-common = { workspace = true }