[package]
name = "fuzzer"
version.workspace = true
edition.workspace = true

[[bin]]
name = "fuzzer"
path = "src/main.rs"

[dependencies]
fuzzer-core = { path = "../../crates/fuzzer-core" }
sui-fuzzer = { path = "../../crates/sui-fuzzer" }

clap = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
